# Background and foreground colors
background = #040303
foreground = #ffffff

# Standard colors
palette = 0=#040303
palette = 1=#F82A2A
palette = 2=#D1D2D1
palette = 3=#fef348
palette = 4=#aaacac
palette = 5=#f76e78
palette = 6=#babbbb
palette = 7=#F3F3F3

# Bright colors
palette = 8=#7f6e6e
palette = 9=#ff7f7f
palette = 10=#ffffff
palette = 11=#fff9a3
palette = 12=#d8d9d9
palette = 13=#ffc2c7
palette = 14=#e8e9e9
palette = 15=#ffffff
