# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(aaacac)
$secondaryBorderColor = rgb(000000)

# --- Theme Variables ---
$white = rgb(aaacac)  
$black = rgb(000000)

general {
    col.active_border = $black $black $black $white $black $black $black $white 25deg
    col.inactive_border = $black
    border_size = 3
    gaps_in = 3
    gaps_out = 3

}

group {
    col.border_active = $activeBorderColor
    
}

decoration {
    rounding = 0
    active_opacity = 1.98
    inactive_opacity = 1.92
    fullscreen_opacity = 1.0
}

animations {
    enabled = yes

    bezier = easeSoft, 0.18, 0.62, 0.32, 1.00
    bezier = easeFade, 0.28, 0.00, 0.22, 1.00

    animation = windows,          1, 2.6, easeSoft
    animation = windowsIn,        1, 2.4, easeSoft
    animation = windowsOut,       1, 2.2, easeFade
    animation = windowsMove,      1, 2.8, easeSoft

    animation = fade,             1, 2.2, easeFade
    animation = fadeIn,           1, 2.0, easeSoft
    animation = fadeOut,          1, 1.8, easeFade
    animation = fadeDim,          1, 1.8, easeFade

    animation = layers,           1, 2.2, easeSoft
    animation = layersIn,         1, 2.0, easeSoft
    animation = layersOut,        1, 1.8, easeFade

    animation = workspaces,       1, 2.4, easeSoft
    animation = specialWorkspace, 1, 2.2, easeSoft

    animation = border,           1, 2.8, easeSoft
    animation = borderangle, 1, 150, linear, loop
    animation = fadeSwitch,       1, 1.4, easeFade
}
